### PR TITLE
deleted line-height to fix the display of the adminbadge on firefox, …

### LINKED ISSUE #512: [FIREFOX] admin / friend emblems get cut of on the bottom
screen shot 2017-05-16 at 12 21 45

### PR DESCRIPTION
**Pull request by tomoversluizen**
…fixed #512

### CODE REVIEW

**Comment by IanCStewart** [comment]
U are trying to fix something that is not an issue here. If text badges get passed through `textBadge` the `getStyle` function will set the `lineHeight` to `22px`

File: src/list-item/styles.js [hunk 1]
```diff
@@ -72,7 +72,7 @@ export default {
     fontWeight: 'normal',
     marginBottom: 0,
     marginTop: '2.4px',
-    lineHeight: '16px',
```
Comment (IanCStewart) [inline src/list-item/styles.js]: Revert this

File: src/admin-badge/styles.js [hunk 2]
```diff
@@ -5,7 +5,6 @@ const styleSheet = {
     backgroundColor: colors.theme,
     color: colors.white,
     fontSize: '10px',
-    lineHeight: '10px',
```
Comment (IanCStewart) [inline src/admin-badge/styles.js]: revert this
